java_library(
    name = "extras",
    srcs = glob(["src/main/java/com/google/gson/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:javax_annotation_jsr250_api",
    ],
)
