java_library(
    name = "metrics",
    srcs = glob(["src/main/java/com/google/gson/metrics/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//gson",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_caliper_caliper",
        "@maven//:com_google_guava_guava",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_google_caliper_caliper_api",
    ],
)
